### ISSUE TITLE
Add rest exception handling

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#18] opened 2016-11-17 03:25 UTC
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/ControllerAdvice.html

**Comment by gala-dan** [comment] 2017-12-04 13:02
A blog explaining a little bit about @ControllerAdvice - https://lankydanblog.com/2017/09/12/global-exception-handling-with-controlleradvice/

**Comment by j-barber** [comment] 2018-02-27 14:40
Closing as duplicate of #14

**Closed by j-barber** 2018-02-27 14:40 UTC
