### ISSUE TITLE
Add to do to check jvm args

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#12] opened 2016-09-30 02:38 UTC

**Comment by j-barber** [comment] 2016-12-09 14:02
Is this a duplicate of #5 (JVM args)?

**Comment by GalateaRaj** [comment] 2016-12-09 19:27
This one is to add a //TODO:  in Fuse code somewhere (or on a checklist) to make sure the application developer who is using FUSE double checks that the JVM args are relevant to their project.

#5 is actually to come up with FUSE recommended JVM args.

**Comment by GalateaEric** [comment] 2018-06-26 17:01
closing as duplicate of #5 for the time being.

**Closed by GalateaEric** 2018-06-26 17:01 UTC
