### ISSUE TITLE
Demonstrate how to return exceptions in spring rest

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#14] opened 2016-10-06 10:29 UTC
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

Write custom handler to translate exception message to something that is returned to caller.

**Comment by GalateaEric** [comment] 2017-11-30 16:48
sort of duplicate of #92

**Comment by gala-lightfoot** [comment] 2018-02-27 11:21
https://github.com/GalateaRaj/fuse-starter-java/pull/130

**Comment by paulo-reichert** [comment] 2018-02-27 13:05
One example of an exception that we could handle to provide a more friendly user message is this:

```
{
    "timestamp": 1519736514113,
    "status": 400,
    "error": "Bad Request",
    "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
    "message": "JSON parse error: Can not construct instance of org.galatea.starter.domain.TradeAgreement, problem: instrument; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.galatea.starter.domain.TradeAgreement, problem: instrument\n at [Source: java.io.PushbackInputStream@b098d28; line: 8, column: 2] (through reference chain: java.util.ArrayList[0])",
    "path": "/settlementEngine"
}
```

It's thrown when an invalid 'TradeAgreement' is sent to the service. While the status and error are ok, the exception name and the message could be improved to something that is more application specific. 

The exception handler should also have hooks for other exceptions that may happen in other layers of our code, not only the REST controller, and handle those in a standard way (i.e. return errors 5xx with user-friendly message).

**Comment by j-barber** [comment] 2018-02-27 14:40
This issue is duplicated by #18.

**Closed** 2018-03-06 15:46 UTC
