### ISSUE TITLE
Demonstrate how to best use the checker framework

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#54] opened 2017-01-04 18:25 UTC
https://blogs.oracle.com/java-platform-group/entry/java_8_s_new_type

**Comment by paulo-reichert** [comment] 2018-02-22 14:06
Is this the same or overlapping with #106?

**Comment by paulo-reichert** [comment] 2018-03-06 12:57
Closing as duplicate of #106.

**Closed by paulo-reichert** 2018-03-06 12:57 UTC
Labels: Input Wanted
