### ISSUE TITLE
Set up jenkins builds per best practices

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#84] opened 2017-11-28 14:03 UTC
We should have these builds defined in our jenkins pipeline file:

Branch build (if supported by Github) – triggered off commits to a bugfix, feature, or hotfix branch but NOT a release branch
1. Compile code
2. Run sonar and fail if we don't meet the quality gate
3. Run checkstyle and fail if we have violations
4. Run Junits and fail if tests fail

PR Build – triggered off PRs
1. Run all steps from branch build
2. Mark build as unstable if we don't have sufficient test coverage.   Provide an example of how to exclude certain classes/methods when figuring out code coverage using the gradle plugin for jacoco.  Note that Jacoco and lombok don't play nicely together at the moment (ie there is no good way to get jacoco to exclude lombok generated methods), however the upcoming release to jacoco should address this.  See this group for the discussion: https://groups.google.com/forum/#!forum/jacoco  . 
3. Deploy app to cloud foundry and create any necessary services
4. Run integration tests
5. Shut down app on cloud foundry
6. Report PR build status back to GitHub

Develop Build -- triggered off commits to develop branch
1. Run steps 1-4 in PR Build
2. Run performance tests
5. Shut down app on cloud foundry

**Comment by gala-dan** [comment] 2017-12-13 16:05
We currently have a Jenkins pipeline set-up that follows the above pattern.

Outstanding tasks:

1. Trigger builds automatically for PR
2. Jacoco step from above, although SonarQube quality gate will fail if we don't have sufficient coverage
3. Missing shutdown step

**Comment by gala-dan** [comment] 2017-12-13 16:32
Regarding 3, it seems the Cloud Foundry Jenkins plugin doesn't provide any way of stopping an application. Appears we'll need to install CF on the Jenkins server and manually call the `cf stop APP_NAME` command within a timeout.

**Comment by gala-dan** [comment] 2017-12-14 13:55
Regarding 1, the GitHub PR Build plugin has been installed, and a common shared secret has been supplied to both the plugin config and the GitHub webhook. Waiting for PR to be submitted before can test.

**Comment by gala-dan** [comment] 2017-12-15 11:28
Regarding 2, Eric is currently working on migration to Gradle from Maven so will change anyway.

**Comment by j-barber** [comment] 2018-02-15 15:23
Confirmed -- unit test failures fail the build:
https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/job/feature%252Fissue-84-test-build-failure-scenarios/1/

**Comment by j-barber** [comment] 2018-02-15 15:24
Confirmed -- sonar quality gate failures fail the build:
https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/job/feature%252Fissue-84-test-build-failure-scenarios/2/console

![image](https://user-images.githubusercontent.com/23705265/36264279-56572998-123a-11e8-90b1-52575fa7472e.png)

**Comment by j-barber** [comment] 2018-02-15 15:29
Features left to implement/test from the original requirements are:
1. Trigger build automatically off of PR _[covered in new issue #115]_
2. Confirm checkstyle violations fail a build (do we need checkstyle given we have Sonar?) _[Decided we don't. Will remove under issue #135]_
3. Mark a build unstable if <X% code coverage (this would currently fail the build if the Sonar QualityGate for code coverage wasn't met, rather than mark Unstable)
4. Performance tests (we run the stage, but don't have any defined/implemented)

I vote to close this issue after agreeing what we want for points 2 and 3. 
Can we remove checkstyle?
Are we fine w/ build failures due to lack of code coverage?

**Comment by j-barber** [comment] 2018-02-22 13:31
Closing issue since most of the original points have been covered. A few other follow ups have spawned their own issues. (documented above).

**Closed as completed by j-barber** 2018-02-22 13:31 UTC
Labels: co:devops
