### ISSUE TITLE
Expose spring actuator endpoints 

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#27] opened 2016-12-05 13:38 UTC
However make sure we have the right level of authentication. 

Perhaps some endpoints (e.g. shutdown) should only be accessible from the host running the jvm.

**Comment by adelsam** [comment] 2017-01-18 21:33
http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready.html

**Comment by j-barber** [comment] 2018-02-27 14:43
Duplicate of issue #6.

**Closed by j-barber** 2018-02-27 14:43 UTC
