### ISSUE TITLE
Add an example of calling an upstream rest service

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#85] opened 2017-11-28 16:02 UTC
Along with examples of how to test it.

**Comment by j-barber** [comment] 2018-02-06 21:21
I propose we close this issue as a duplicate of #23

**Comment by paulo-reichert** [comment] 2018-02-22 13:58
Do we want to show anything more than what is shown in `SettlementRestControllerIntegrationTest.java`?

Assuming we're using feign, is there any testable code to write?

**Comment by j-barber** [comment] 2018-02-22 14:09
Also, #23 and #85 are duplicates of each other. We should consolidate to one.

And agree w/ Paulo's question, anything left to show?

**Comment by paulo-reichert** [comment] 2018-03-05 20:06
Closing this as we don't know whether there's anything worth illustrating at this point.

**Closed as completed by paulo-reichert** 2018-03-05 20:06 UTC
Labels: st:input-wanted
