### ISSUE TITLE
Use REST assured rather than MockMvc for our REST controller unit tests

### ISSUE THREAD

**Issue by GalateaEric** [GalateaRaj/fuse-starter-java#287] opened 2019-08-07 19:42 UTC
Issue Description
--
Use REST assured rather than MockMvc for our REST controller unit tests.

http://rest-assured.io/

Design
--
[Description of the root cause for the issue and how to resolve it. Should be complete before Review is approved]

Documentation Changes
--
[Description of changes necessary to the Fuse documentation due to the changes in response to this issue. Should be complete before Review is approved]

Test Evidence
--
[include relevant tests and output. Should be complete before Review is approved]

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by GalateaTom** [comment] 2019-09-11 15:37
Notes on why certain design decisions were made in #287 feature branch:
- As this is unit testing of SettlementRestController I attempted to use as few other classes as possible, hence why I did not include the @WebMvcTest annotation.  
- Originally there were issues getting SettlementRestController to pickup the various properties from application.properties.  This was resolved by the PropertyConfig class in SettlementRestControllerTest and annotating settlementRestController with @Autowired.  This meant that SettlementRestController could assign values to the settleMissionPath and getMissionPath variables, but the properties were not passed into the @PostMapping, @GetMapping, @PutMapping or @DeleteMapping blocks
- After reading https://stackoverflow.com/a/47221283 I found that in order for the properties to be included in @PostMapping, @GetMapping, @PutMapping and @DeleteMapping calls to addPlaceholderValue had to be included in the call to RestAssuredMockMvc.standaloneSetup
- The MappingJackson2HttpMessageConverter and Jaxb2RootElementHttpMessageConverter converters were added because without them there were issues parsing the JSON and XML being returned by SettlementRestController.  Solution found after reading https://stackoverflow.com/q/12514285
- setContentNegotiationManager used so that the "format" parameter used in testGetMissionsFound_XML can be used.  In practice this work would be done thanks to the method MvcConfig.configureContentNegotiation

**Comment by GalateaTom** [comment] 2019-09-12 15:19
Notes on design decisions in FuseHttpTraceFilterTest class
- Test class created because SettlementRestControllerTest no longer calls FuseHttpTraceFilter and therefore we can no longer test the contents of the header in that class
- Individual tests in FuseHttpTraceFilterTest are the tests that were originally in SettlementRestControllerTest and called SettlementRestControllerTest.verifyAuditHeaders before I picked up this issue.  Those tests have been altered to use RestAssured and we're no longer checking the response to any requests, just the headers
- SettlementRestControllerTest was designed to be as much of a unit test as possible, therefore we included more configuration in the RestAssuredMockMvc.standAloneSetup rather than instantiate classes like FuseHttpTraceFilter.  In FuseHttpTraceFilterTest the entire application context is created because we need other beans in order for requests to be processed and the methods in FuseHttpTraceFilter called.
- Original intention was to use @WebMvcTest annotation (https://spring.io/guides/gs/testing-web/) but the tests were then failing with "ConnectException: Connection refused".  I found the solution to switch to @SpringBootTest (https://stackoverflow.com/a/40666234)

**Closed as completed** 2020-02-14 20:38 UTC
Labels: it:enhancement, cx:intermediate, st:ready, co:web-service
